server:
    port: 8083

spring:
  r2dbc:
    url: r2dbc:h2:file:///./test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
    password: password
  security:
    user:
      name: user
      password: 1234

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

h2-server:
  port: 8081

logging:
  level:
    root: INFO

# jwt:
#   secret: 2024
#   timeExpire: 120
#   acceptExpire: 30