server:
    port: 8085

spring:
  r2dbc:
    url: r2dbc:h2:mem:///escueladb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    initialization-mode: always

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true